// react/src/agent-selector.js
import React, { Component } from 'react';
import { getAgents } from './agent-service';

export default class AgentSelector extends Component {

  state = {
    title: 'Select an agent',
    agents: getAgents(),
  }

  handleClick = agentIndex => {
    const agentName = this.state.agents[agentIndex];
    this.setState({
      selectedAgent: agentName,
      title: `You selected agent: ${agentName}`
    });
  }

  render() {
    const { agents, title, selectedAgent } = this.state;
    const agentStyle = agent => ({
      fontSize: 40,
      border: '1px solid',
      backgroundColor: agent === selectedAgent ? 'green' : 'inherit',
    });
    return (
      <div>
        <h1 style={{display: 'flex', justifyContent: 'center'}}>
          {title}
        </h1>
        <ul>
          {agents.map((agent, i) =>
            <li key={agent} style={agentStyle(agent)} >
              {agent}
              <button onClick={() => this.handleClick(i)}>
                Select this agent
              </button>
            </li>
          )}
        </ul>
      </div>
    );
  }
}

// src/app/agent-selector.component.ts
import { Component } from '@angular/core';
import { AgentService } from './agent.service';

@Component({
  selector: 'app-root',
  templateUrl: './agent-selector.component.html',
  styleUrls: ['./agent-selector.component.css']
})
export class AgentSelectorComponent {

  agents: Array<string>;

  constructor(
    agentService: AgentService,
  ) {
    this.agents = agentService.getAgents();
  }

  title = 'Click one of the things';

  handleClick(agentIndex: number) {
    const agentName = this.agents[agentIndex];
    this.title = `You selected agent: ${agentName}`;
  }
}

<div>
  <h1>{{title}}</h1>
  <ul>
    <li
      *ngFor="let agent of agents; let i=index"
      style="font-size: 40px; border: 1px solid black"
      >
      {{agent}}
      <button (click)="handleClick(i)">
        Select this agent
      </button>
    </li>
  </ul>
</div>
